// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: grpc/onetimecode.proto

package grpc

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OneTimeCodeGen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
}

func (x *OneTimeCodeGen) Reset() {
	*x = OneTimeCodeGen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_onetimecode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneTimeCodeGen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneTimeCodeGen) ProtoMessage() {}

func (x *OneTimeCodeGen) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_onetimecode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneTimeCodeGen.ProtoReflect.Descriptor instead.
func (*OneTimeCodeGen) Descriptor() ([]byte, []int) {
	return file_grpc_onetimecode_proto_rawDescGZIP(), []int{0}
}

func (x *OneTimeCodeGen) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

type ReadCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ReadCodeReq) Reset() {
	*x = ReadCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_onetimecode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCodeReq) ProtoMessage() {}

func (x *ReadCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_onetimecode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCodeReq.ProtoReflect.Descriptor instead.
func (*ReadCodeReq) Descriptor() ([]byte, []int) {
	return file_grpc_onetimecode_proto_rawDescGZIP(), []int{1}
}

func (x *ReadCodeReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type OneTimeCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	ExpiresAt  int64  `protobuf:"varint,2,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	Value      string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *OneTimeCodeResponse) Reset() {
	*x = OneTimeCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_onetimecode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneTimeCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneTimeCodeResponse) ProtoMessage() {}

func (x *OneTimeCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_onetimecode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneTimeCodeResponse.ProtoReflect.Descriptor instead.
func (*OneTimeCodeResponse) Descriptor() ([]byte, []int) {
	return file_grpc_onetimecode_proto_rawDescGZIP(), []int{2}
}

func (x *OneTimeCodeResponse) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *OneTimeCodeResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *OneTimeCodeResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_grpc_onetimecode_proto protoreflect.FileDescriptor

var file_grpc_onetimecode_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6f, 0x6e, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x63, 0x6f,
	0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6f, 0x74, 0x63, 0x67, 0x6f, 0x22,
	0x30, 0x0a, 0x0e, 0x4f, 0x6e, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x47, 0x65,
	0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x22, 0x23, 0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x69, 0x0a, 0x13, 0x4f, 0x6e, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x1c, 0x0a,
	0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x32, 0x95, 0x01, 0x0a, 0x12, 0x4f, 0x6e, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x15, 0x2e, 0x6f, 0x74, 0x63, 0x67, 0x6f, 0x2e, 0x4f,
	0x6e, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x47, 0x65, 0x6e, 0x1a, 0x1a, 0x2e,
	0x6f, 0x74, 0x63, 0x67, 0x6f, 0x2e, 0x4f, 0x6e, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x08, 0x52,
	0x65, 0x61, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x2e, 0x6f, 0x74, 0x63, 0x67, 0x6f, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x6f, 0x74,
	0x63, 0x67, 0x6f, 0x2e, 0x4f, 0x6e, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x67, 0x72, 0x70,
	0x63, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_onetimecode_proto_rawDescOnce sync.Once
	file_grpc_onetimecode_proto_rawDescData = file_grpc_onetimecode_proto_rawDesc
)

func file_grpc_onetimecode_proto_rawDescGZIP() []byte {
	file_grpc_onetimecode_proto_rawDescOnce.Do(func() {
		file_grpc_onetimecode_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_onetimecode_proto_rawDescData)
	})
	return file_grpc_onetimecode_proto_rawDescData
}

var file_grpc_onetimecode_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_onetimecode_proto_goTypes = []interface{}{
	(*OneTimeCodeGen)(nil),      // 0: otcgo.OneTimeCodeGen
	(*ReadCodeReq)(nil),         // 1: otcgo.ReadCodeReq
	(*OneTimeCodeResponse)(nil), // 2: otcgo.OneTimeCodeResponse
}
var file_grpc_onetimecode_proto_depIdxs = []int32{
	0, // 0: otcgo.OneTimeCodeService.CreateCode:input_type -> otcgo.OneTimeCodeGen
	1, // 1: otcgo.OneTimeCodeService.ReadCode:input_type -> otcgo.ReadCodeReq
	2, // 2: otcgo.OneTimeCodeService.CreateCode:output_type -> otcgo.OneTimeCodeResponse
	2, // 3: otcgo.OneTimeCodeService.ReadCode:output_type -> otcgo.OneTimeCodeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_onetimecode_proto_init() }
func file_grpc_onetimecode_proto_init() {
	if File_grpc_onetimecode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_onetimecode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneTimeCodeGen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_onetimecode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_onetimecode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneTimeCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_onetimecode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_onetimecode_proto_goTypes,
		DependencyIndexes: file_grpc_onetimecode_proto_depIdxs,
		MessageInfos:      file_grpc_onetimecode_proto_msgTypes,
	}.Build()
	File_grpc_onetimecode_proto = out.File
	file_grpc_onetimecode_proto_rawDesc = nil
	file_grpc_onetimecode_proto_goTypes = nil
	file_grpc_onetimecode_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OneTimeCodeServiceClient is the client API for OneTimeCodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OneTimeCodeServiceClient interface {
	CreateCode(ctx context.Context, in *OneTimeCodeGen, opts ...grpc.CallOption) (*OneTimeCodeResponse, error)
	ReadCode(ctx context.Context, in *ReadCodeReq, opts ...grpc.CallOption) (*OneTimeCodeResponse, error)
}

type oneTimeCodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOneTimeCodeServiceClient(cc grpc.ClientConnInterface) OneTimeCodeServiceClient {
	return &oneTimeCodeServiceClient{cc}
}

func (c *oneTimeCodeServiceClient) CreateCode(ctx context.Context, in *OneTimeCodeGen, opts ...grpc.CallOption) (*OneTimeCodeResponse, error) {
	out := new(OneTimeCodeResponse)
	err := c.cc.Invoke(ctx, "/otcgo.OneTimeCodeService/CreateCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oneTimeCodeServiceClient) ReadCode(ctx context.Context, in *ReadCodeReq, opts ...grpc.CallOption) (*OneTimeCodeResponse, error) {
	out := new(OneTimeCodeResponse)
	err := c.cc.Invoke(ctx, "/otcgo.OneTimeCodeService/ReadCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OneTimeCodeServiceServer is the server API for OneTimeCodeService service.
type OneTimeCodeServiceServer interface {
	CreateCode(context.Context, *OneTimeCodeGen) (*OneTimeCodeResponse, error)
	ReadCode(context.Context, *ReadCodeReq) (*OneTimeCodeResponse, error)
}

// UnimplementedOneTimeCodeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOneTimeCodeServiceServer struct {
}

func (*UnimplementedOneTimeCodeServiceServer) CreateCode(context.Context, *OneTimeCodeGen) (*OneTimeCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCode not implemented")
}
func (*UnimplementedOneTimeCodeServiceServer) ReadCode(context.Context, *ReadCodeReq) (*OneTimeCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadCode not implemented")
}

func RegisterOneTimeCodeServiceServer(s *grpc.Server, srv OneTimeCodeServiceServer) {
	s.RegisterService(&_OneTimeCodeService_serviceDesc, srv)
}

func _OneTimeCodeService_CreateCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OneTimeCodeGen)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OneTimeCodeServiceServer).CreateCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otcgo.OneTimeCodeService/CreateCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OneTimeCodeServiceServer).CreateCode(ctx, req.(*OneTimeCodeGen))
	}
	return interceptor(ctx, in, info, handler)
}

func _OneTimeCodeService_ReadCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OneTimeCodeServiceServer).ReadCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otcgo.OneTimeCodeService/ReadCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OneTimeCodeServiceServer).ReadCode(ctx, req.(*ReadCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _OneTimeCodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "otcgo.OneTimeCodeService",
	HandlerType: (*OneTimeCodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCode",
			Handler:    _OneTimeCodeService_CreateCode_Handler,
		},
		{
			MethodName: "ReadCode",
			Handler:    _OneTimeCodeService_ReadCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/onetimecode.proto",
}
